language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0 
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode

# script: bundle exec rspec spec
env:
  - JAVA_OPTS="-server -Djruby.cext.enabled=false -Djruby.compile.invokedynamic=false"

notifications:
  irc: "irc.freenode.net#rubberec2"
