# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubber}
  s.version = "2.0.0.rails3"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Conway"]
  s.date = %q{2010-04-09}
  s.default_executable = %q{vulcanize}
  s.description = %q{The rubber plugin enables relatively complex multi-instance deployments of RubyOnRails applications to Amazon's Elastic Compute Cloud (EC2).  Like capistrano, rubber is role based, so you can define a set of configuration files for a role and then assign that role to as many concrete instances as needed. One can also assign multiple roles to a single instance. This lets one start out with a single ec2 instance (belonging to all roles), and add new instances into the mix as needed to scale specific facets of your deployment, e.g. adding in instances that serve only as an 'app' role to handle increased app server load.}
  s.email = %q{matt@conwaysplace.com}
  s.executables = ["vulcanize"]
  s.extra_rdoc_files = [
    "README",
     "TODO"
  ]
  s.files = [
    "CHANGELOG",
     "COPYING",
     "README",
     "TODO",
     "VERSION",
     "bin/vulcanize",
     "lib/capistrano/hostcmd.rb",
     "lib/rubber.rb",
     "lib/rubber/capistrano.rb",
     "lib/rubber/cloud.rb",
     "lib/rubber/cloud/aws.rb",
     "lib/rubber/cloud/base.rb",
     "lib/rubber/configuration.rb",
     "lib/rubber/dns.rb",
     "lib/rubber/dns/base.rb",
     "lib/rubber/dns/dyndns.rb",
     "lib/rubber/dns/nettica.rb",
     "lib/rubber/dns/zerigo.rb",
     "lib/rubber/environment.rb",
     "lib/rubber/generator.rb",
     "lib/rubber/instance.rb",
     "lib/rubber/recipes/rubber.rb",
     "lib/rubber/recipes/rubber/bundles.rb",
     "lib/rubber/recipes/rubber/deploy.rb",
     "lib/rubber/recipes/rubber/instances.rb",
     "lib/rubber/recipes/rubber/load_balancers.rb",
     "lib/rubber/recipes/rubber/security_groups.rb",
     "lib/rubber/recipes/rubber/setup.rb",
     "lib/rubber/recipes/rubber/spot_requests.rb",
     "lib/rubber/recipes/rubber/static_ips.rb",
     "lib/rubber/recipes/rubber/utils.rb",
     "lib/rubber/recipes/rubber/volumes.rb",
     "lib/rubber/tasks/rubber.rb",
     "lib/rubber/util.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/wr0ngway/rubber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rubber}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A capistrano plugin for managing multi-instance deployments to the cloud (ec2)}
  s.test_files = [
    "test/environment_test.rb",
     "test/generator_test.rb",
     "test/instance_test.rb",
     "test/test_helper.rb",
     "test/util_test.rb",
     "test/zerigo_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.4.0"])
      s.add_runtime_dependency(%q<amazon-ec2>, [">= 0.9.0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
      s.add_runtime_dependency(%q<nettica>, [">= 0"])
      s.add_runtime_dependency(%q<zerigo_dns>, [">= 0"])
      s.add_runtime_dependency(%q<railties>, ["= 3.0.0.beta2"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.4.0"])
      s.add_dependency(%q<amazon-ec2>, [">= 0.9.0"])
      s.add_dependency(%q<aws-s3>, [">= 0"])
      s.add_dependency(%q<nettica>, [">= 0"])
      s.add_dependency(%q<zerigo_dns>, [">= 0"])
      s.add_dependency(%q<railties>, ["= 3.0.0.beta2"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.4.0"])
    s.add_dependency(%q<amazon-ec2>, [">= 0.9.0"])
    s.add_dependency(%q<aws-s3>, [">= 0"])
    s.add_dependency(%q<nettica>, [">= 0"])
    s.add_dependency(%q<zerigo_dns>, [">= 0"])
    s.add_dependency(%q<railties>, ["= 3.0.0.beta2"])
  end
end

